name: Call AWS Lambda and Comment S3 Link

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Adjust to your branch name
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  call-lambda:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust to your region

      - name: Set and Debug Environment Variables
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          echo "Repository URL: $REPO_URL"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Invoke Lambda function
        env:
          REPO_URL: ${{ env.REPO_URL }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          echo "Using Repository URL: $REPO_URL"
          echo "Using Branch Name: $BRANCH_NAME"
          PAYLOAD=$(jq -n --arg branch "$BRANCH_NAME" --arg url "$REPO_URL" '{type: "github", branch: $branch, url: $url}')
          FINAL_PAYLOAD=$(jq -n --arg body "$PAYLOAD" '{body: $body}')
          echo "Payload: $FINAL_PAYLOAD"
          aws lambda invoke --function-name Core-Engine-Docker --payload "$FINAL_PAYLOAD" response.json --cli-binary-format raw-in-base64-out
          cat response.json
          S3_LINK=$(jq -r '.body' response.json)
          echo "S3_LINK=$S3_LINK" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "S3_LINK: ${{ env.S3_LINK }}"

      - name: Comment on PR or Push
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          S3_LINK: ${{ env.S3_LINK }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_PAT" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
              -d "{\"body\": \"Here is the S3 link: $S3_LINK\"}"
          else
            echo "Pushed to branch: $GITHUB_REF. S3 link: $S3_LINK"
          fi
            
      - name: Process link for workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "S3_LINK=${{ env.S3_LINK }}"
          echo "The S3 link is: $S3_LINK"
          echo "##[group]S3 Link"
          echo "URL: $S3_LINK"
          echo "##[endgroup]"
